var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/dashboard/admin/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0a99en0._.js")
R.c("server/chunks/ssr/node_modules_0vtdjw7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0w74-ah.js")
R.c("server/chunks/ssr/[root-of-the-server]__0.yihlr._.js")
R.c("server/chunks/ssr/node_modules_next_dist_03nkrli._.js")
R.c("server/chunks/ssr/[root-of-the-server]__10_v9f.._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/src_app_dashboard_layout_tsx_0mft_y_._.js")
R.c("server/chunks/ssr/_next-internal_server_app_dashboard_admin_page_actions_0n.v_mc.js")
R.m(58164)
module.exports=R.m(58164).exports
