var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/notifications/route.js")
R.c("server/chunks/[root-of-the-server]__0n3ktv1._.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/[root-of-the-server]__0oxgwjf._.js")
R.c("server/chunks/[root-of-the-server]__0p3fo6l._.js")
R.c("server/chunks/[root-of-the-server]__0fh65py._.js")
R.c("server/chunks/[root-of-the-server]__0u3b4v1._.js")
R.c("server/chunks/_next-internal_server_app_api_notifications_route_actions_0mycgp_.js")
R.m(94483)
module.exports=R.m(94483).exports
