var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/users/[id]/route.js")
R.c("server/chunks/[root-of-the-server]__0jgbbfy._.js")
R.c("server/chunks/node_modules_next_11synfn._.js")
R.c("server/chunks/[root-of-the-server]__0oxgwjf._.js")
R.c("server/chunks/[root-of-the-server]__0p3fo6l._.js")
R.c("server/chunks/[root-of-the-server]__0fh65py._.js")
R.c("server/chunks/[root-of-the-server]__0u3b4v1._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_users_[id]_route_actions_0vl-wdd.js")
R.m(84085)
module.exports=R.m(84085).exports
